@startuml
|Cashier|
     start
        :Enter customer name;
        :Request\nto Application;
    |Application|
        if (Data Correctly) then (Invalid Data)
          :Print error\n message;
          stop
        else (Valid Data)
          :Request to\n     Bank;
        :Request to\n Database;
    |Database|
        :Add data\nin logfile;
        :Sends a list\nwith the names\nof all users;
    |Application|
        if (Is this a new customer?) then (Yes)
          :Send error\n message;
|Application|
        :Print message;
      stop
    else (No)
    :Database query : user history?;
|Database|
    :Send full\ncustomer history;
|Application|
        :Print full history;
|Cashier|
        if (Do I need a detailed history?) then (No)
        stop
|Cashier|           
        else (Yes)
        :Enter the time span;
        |Application|
            :Print ditailed history;
        endif
        stop
@enduml

    start
    :Enter customer name;
    :Request\nto Application;
|Application|
    if (Data Correctly) then (Invalid Data)
      :Print error\n message;
      stop
    else (Valid Data)
      :Request to\n     Bank;
    :Request to\n Database;
|Database|
    :Add data\nin logfile;
    :Sends a list\nwith the names\nof all users;
|Application|
    if (Is this a new customer?) then (No)
    :;
|Application|
        :Print message;
      stop